[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    knolleary/PubSubClient@^2.8
    olikraus/U8g2@^2.36.15
build_flags =
    -DCORE_DEBUG_LEVEL=3
