[platformio]
default_envs = waveshare_s3_2inch

[env:waveshare_s3_base]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_WAVESHARE_FAMILY=1
lib_deps =
    knolleary/PubSubClient@^2.8
    moononournation/Arduino_GFX@^1.6.1

[env:waveshare_s3_2inch]
extends = env:waveshare_s3_base
build_flags =
    ${env:waveshare_s3_base.build_flags}
    -DBOARD_WAVESHARE_S3_2INCH=1

[env:waveshare_s3_1_47inch]
extends = env:waveshare_s3_base
build_flags =
    ${env:waveshare_s3_base.build_flags}
    -DBOARD_WAVESHARE_S3_1_47INCH=1

[env:waveshare_s3_7inch]
extends = env:waveshare_s3_base
build_flags =
    ${env:waveshare_s3_base.build_flags}
    -DBOARD_WAVESHARE_S3_7INCH=1
